# This is a basic workflow that is manually triggered

name: Watch hitomi.la file changes

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  watchdiff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: watchdiff
      - name: Download files
        run: ./fetch.sh
      - name: Commit and Push
        id: push
        run: |
            git config --global user.name 'Watchdiff bot'
            git config --global user.email 'tom5079@naver.com'
            { git add . && git commit -m "File update" && git push; } | tail -1 | grep -q "nothing to commit" || curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"<@&938174944305610792> :bell: :bell: :bell: :bell: :bell: :bell: :bell: :bell: \`\`\`$(git diff HEAD^ HEAD --stat | sed -z 's/\n/\\n/g')\`\`\`\"}" ${{ secrets.DISCORD_WEBHOOK }} && $(exit 1)
